### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by HanGyeongjun** [likelion11-kangwon/PikachuCodingWarmUp#1]
프로젝트 운영을 위한 Git 레포 초기 설정을 진행합니다.

### TODO

- [x] gitignore 설정
- [x] README 파일 추가
- [x] Branch 보호 설정
- [x] Issue 및 PR 템플릿 작성
- [x] Git Conventions Wiki 작성
- [x] 태그 등의 기타 설정

**Comment by HanGyeongjun** [comment]
main에 바로 진행했으므로 별도의 PR / Merge 없이 이슈 닫겠습니다.
